import { defineConfig, drivers } from '@adonisjs/core/encryption'
import env from '#start/env'

/**
 * Encryption configuration.
 *
 * The application uses AES-256-GCM, an authenticated cipher, so that
 * tampered payloads are rejected when they are decrypted. The key is the
 * APP_KEY generated by "node ace generate:key".
 */
const encryptionConfig = defineConfig({
  /**
   * Encryptor used when no encryptor is explicitly requested.
   */
  default: 'app',

  list: {
    app: drivers.aes256gcm({
      /**
       * Identifier of the encryptor. It is stored inside the encrypted
       * payload, so it must not be renamed without keeping the old key
       * around to decrypt previously encrypted values.
       */
      id: 'app',

      /**
       * The first key is used to encrypt, all of them are tried to
       * decrypt. Add previous keys here when rotating.
       */
      keys: [env.get('APP_KEY')],
    }),
  },
})

export default encryptionConfig
